# Generated by Django 2.2.5 on 2019-09-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
